# Generated by Django 2.2 on 2023-08-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followchart',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
